name: GitHub Actions Build and Deploy Demo

# 当 master 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - master

jobs:
  # job-id:
  build-and-deploy:
    name: 构建并部署
    runs-on: ubuntu-18.04
    steps:
      # 获取源码
      - name: Checkout
        uses: actions/checkout@master

      # 构建并部署
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.MY_COURSE_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
          BUILD_SCRIPT: npm install && npm run build:docs